/**
 * `virtual:pwa-register/react`, for the suite.
 *
 * ⚠️ The real module is generated by `vite-plugin-pwa` at BUILD time, and the
 * vitest config does not run that plugin — deliberately: registering a service
 * worker during a unit test caches around jsdom and produces failures that have
 * nothing to do with the test. Without this alias the import fails to resolve
 * and every test in the file that mounts the shell disappears, which reads as
 * "7 tests were deleted" rather than as an error.
 *
 * `needRefresh` is false, so `UpdateToast` renders nothing: there is no waiting
 * worker in a test, which is the honest answer rather than a convenient one.
 */
export function useRegisterSW(_options?: { onRegisterError?: (err: unknown) => void }): {
  needRefresh: [boolean, (v: boolean) => void];
  offlineReady: [boolean, (v: boolean) => void];
  updateServiceWorker: (reload?: boolean) => Promise<void>;
} {
  return {
    needRefresh: [false, () => {}],
    offlineReady: [false, () => {}],
    updateServiceWorker: async () => {},
  };
}
