import {
  AlertTriangle,
  ArrowLeftRight,
  Ban,
  BarChart3,
  Bell,
  Calendar,
  CalendarCheck,
  Check,
  CircleCheck,
  Clock,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  CircleDot,
  ClipboardList,
  Download,
  Eye,
  FileText,
  Globe,
  HeartHandshake,
  Home,
  Info,
  Key,
  LayoutGrid,
  Layers,
  List,
  LogIn,
  LogOut,
  SquareCheckBig,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  Pencil,
  Phone,
  PhoneCall,
  Plus,
  RefreshCw,
  Scroll,
  Search,
  Settings,
  Shield,
  SlidersHorizontal,
  Stethoscope,
  Sun,
  Target,
  Ticket,
  Trash2,
  LockOpen,
  Mail,
  MoreHorizontal,
  User,
  UserPlus,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * Semantic icon name → lucide component.
 *
 * Nav items and buckets carry a NAME (from @msr/volunteering), not a glyph, so the
 * server never ships presentation and the icon set can change in one place.
 */
const REGISTRY: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'arrow-left-right': ArrowLeftRight,
  ban: Ban,
  'bar-chart': BarChart3,
  bell: Bell,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  check: Check,
  'check-square': SquareCheckBig,
  info: Info,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'circle-dot': CircleDot,
  'clipboard-list': ClipboardList,
  download: Download,
  eye: Eye,
  'file-text': FileText,
  globe: Globe,
  'heart-handshake': HeartHandshake,
  home: Home,
  key: Key,
  'layout-grid': LayoutGrid,
  'list-view': List,
  'lock-open': LockOpen,
  'log-out': LogOut,
  mail: Mail,
  'more-horizontal': MoreHorizontal,
  layers: Layers,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  moon: Moon,
  pencil: Pencil,
  phone: Phone,
  'phone-call': PhoneCall,
  plus: Plus,
  refresh: RefreshCw,
  scroll: Scroll,
  search: Search,
  settings: Settings,
  shield: Shield,
  sliders: SlidersHorizontal,
  stethoscope: Stethoscope,
  sun: Sun,
  target: Target,
  ticket: Ticket,
  trash: Trash2,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  clock: Clock,
  'circle-check': CircleCheck,
  'log-in': LogIn,
  x: X,
};

/** Every name `Icon` knows. Exported so a caller naming a glyph can be
 *  checked against it — an unknown name renders a generic dot in silence. */
export const ICON_NAMES: string[] = Object.keys(REGISTRY);

export function Icon({
  name,
  size = 17,
  color = 'currentColor',
  strokeWidth = 1.9,
}: {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const Cmp = REGISTRY[name] ?? CircleDot;
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} aria-hidden />;
}
