-- Generated by `prisma migrate dev` to close the drift between the hand-written
-- SQL of the declarations and form-builder migrations and what schema.prisma
-- describes. Two kinds of difference, both already the convention everywhere
-- else in this schema:
--
--   * `id` carries no DEFAULT. The client generates the uuid — check
--     `information_schema.columns`: not one older table has `gen_random_uuid()`.
--   * Foreign keys are re-declared with ON UPDATE CASCADE, which is how Prisma
--     spells every relation it owns.
--
-- ⚠️ Named `20260916000000` and NOT with the UTC stamp Prisma gave it
-- (`20260915171928`). Prisma names in UTC and replays migrations in folder-name
-- order, so its own name sorted BEFORE `20260915210000_declarations` — the
-- migration that creates the tables this one alters — and the shadow-database
-- replay died on `relation "stalls.stall_declaration" does not exist`. The
-- round hours the hand-written migrations use are local time, 5h30m ahead.

-- DropForeignKey
ALTER TABLE "stalls"."stall_declaration" DROP CONSTRAINT "stall_declaration_edition_id_fkey";

-- DropForeignKey
ALTER TABLE "stalls"."stall_declaration_consent" DROP CONSTRAINT "stall_declaration_consent_declaration_id_fkey";

-- DropForeignKey
ALTER TABLE "stalls"."stall_declaration_consent" DROP CONSTRAINT "stall_declaration_consent_request_id_fkey";

-- DropForeignKey
ALTER TABLE "stalls"."stall_form_definition" DROP CONSTRAINT "stall_form_definition_edition_id_fkey";

-- DropForeignKey
ALTER TABLE "stalls"."stall_form_field" DROP CONSTRAINT "stall_form_field_definition_id_fkey";

-- DropForeignKey
ALTER TABLE "stalls"."stall_form_field" DROP CONSTRAINT "stall_form_field_section_id_fkey";

-- DropForeignKey
ALTER TABLE "stalls"."stall_form_section" DROP CONSTRAINT "stall_form_section_definition_id_fkey";

-- AlterTable
ALTER TABLE "stalls"."stall_declaration" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "stalls"."stall_declaration_consent" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "stalls"."stall_form_definition" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "stalls"."stall_form_section" ALTER COLUMN "id" DROP DEFAULT;

-- AddForeignKey
ALTER TABLE "stalls"."stall_declaration" ADD CONSTRAINT "stall_declaration_edition_id_fkey" FOREIGN KEY ("edition_id") REFERENCES "stalls"."stall_edition"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stalls"."stall_declaration_consent" ADD CONSTRAINT "stall_declaration_consent_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "stalls"."stall_request"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stalls"."stall_declaration_consent" ADD CONSTRAINT "stall_declaration_consent_declaration_id_fkey" FOREIGN KEY ("declaration_id") REFERENCES "stalls"."stall_declaration"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stalls"."stall_form_definition" ADD CONSTRAINT "stall_form_definition_edition_id_fkey" FOREIGN KEY ("edition_id") REFERENCES "stalls"."stall_edition"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stalls"."stall_form_section" ADD CONSTRAINT "stall_form_section_definition_id_fkey" FOREIGN KEY ("definition_id") REFERENCES "stalls"."stall_form_definition"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stalls"."stall_form_field" ADD CONSTRAINT "stall_form_field_definition_id_fkey" FOREIGN KEY ("definition_id") REFERENCES "stalls"."stall_form_definition"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stalls"."stall_form_field" ADD CONSTRAINT "stall_form_field_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "stalls"."stall_form_section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
